## Building a GPT

In [1]:
# read it in to inspect it
with open('rammajana.txt', 'r', encoding='UTF-8') as f:
    text = f.read()

In [2]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  182675


In [3]:
# let's look at the first 1000 characters
print(text[:1000])

รามเกียรติ์
ความเป็นมาของเรื่องรามเกียรติ์
รามเกียรติ์ มีที่มาจากเรื่อง รามยณะ ที่ฤาษีวาลมิกิ ชาวอินเดีย แต่งขึ้นเป็นภาษาสันกฤต เมื่อประมาณ 2,400 ปีเศษ มาแล้ว และได้แพร่หลาย จากอินเดียไปยังประเทศใกล้เคียง และได้มีการเพิ่มเติมรายละเอียด ผิดแผกแตกต่างออกไปจากต้นฉบับเดิมไปไม่น้อย  รามยณะเป็นปางหนึ่งในสิบปางของการอวตารมาปราบยุคเข็ญของพระนารายณ์ ที่มีชื่อว่า รามาวตาร สำหรับเรื่องรามเกียรติ์ ของไทยนั้น มีมาแต่สมัยอยุธยา ในสมัยกรุงธนบุรี สมเด็จพระเจ้ากรุงธนบุรี ได้ทรงพระราชนิพนธ์สำหรับให้ละครหลวงเล่น  ปัจจุบันมีอยู่ไม่ครบ ต่อมาในสมัยรัตนโกสินทร์ พระบาทสมเด็จพระพุทธยอดฟ้าฯ ได้ทรงพระราชนิพนธ์ขึ้นเพื่อรวบรวมเรื่องรามเกียรติ์  ซึ่งมีมาแต่เดิมให้ครบถ้วน สมบูรณ์ตั้งแต่ต้นจนจบ พระบาทสมเด็จพระพุทธเลิศหล้าฯ ได้ทรงพระราชนิพนธ์บทละครเรื่องรามเกียรติ์ เพื่อให้ละครหลวงเล่น ได้ทรงเลือกมาเป็นตอน ๆ รามเกียรติ์ นี้จึงมีสำนวนกลอนที่ไพเราะที่สุด พระบาทสมเด็จพระมงกุฎเกล้าทรงพระราชนิพนธ์บทละครเรื่องรามเกียรติ์ โดยดัดแปลงจากพระราชนิพนธ์ของพระบาทสมเด็จพระพุทธเลิศหล้าฯ เพื่อใช้ในการเล่นโขน ซึ่งจะมีอยู่เพียงบางตอนที่

## Tokenization

### Character Token

In [4]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"()*+,-.0123456789:?[]กขคฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลวศษสหฬอฮฯะัาำิีึืุูเแโใไๅๆ็่้๊๋์๐๑๒๓๔๕๖๗๘๙
103


### Subword Token using pyThaiNLP

In [5]:
!pip install pyThaiNLP

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 44.9 MB/s eta 0:00:00


In [14]:
from pythainlp.tokenize import word_tokenize, sent_tokenize

In [16]:
!pip install python-crfsuite

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.9 MB/s eta 0:00:00


In [17]:
#ramayana_token = subword_tokenize(text, engine="wangchanberta")
ramayana_sentence = sent_tokenize(text)

In [19]:
print(len(ramayana_sentence))

2746


In [23]:
ramayana_sentence[:20]

['รามเกียรติ์\nความเป็นมาของเรื่องรามเกียรติ์\nรามเกียรติ์ ',
 'มีที่มาจากเรื่อง รามยณะ ที่ฤาษีวาลมิกิ ชาวอินเดีย แต่งขึ้นเป็นภาษาสันกฤต ',
 'เมื่อประมาณ 2,400 ปีเศษ มาแล้ว ',
 'และได้แพร่หลาย จากอินเดียไปยังประเทศใกล้เคียง ',
 'และได้มีการเพิ่มเติมรายละเอียด ',
 'ผิดแผกแตกต่างออกไปจากต้นฉบับเดิมไปไม่น้อย  ',
 'รามยณะเป็นปางหนึ่งในสิบปางของการอวตารมาปราบยุคเข็ญของพระนารายณ์ ที่มีชื่อว่า รามาวตาร สำหรับเรื่องรามเกียรติ์ ของไทยนั้น มีมาแต่สมัยอยุธยา ในสมัยกรุงธนบุรี ',
 'สมเด็จพระเจ้ากรุงธนบุรี ได้ทรงพระราชนิพนธ์สำหรับให้ละครหลวงเล่น  ',
 'ปัจจุบันมีอยู่ไม่ครบ ',
 'ต่อมาในสมัยรัตนโกสินทร์ พระบาทสมเด็จพระพุทธยอดฟ้าฯ ได้ทรงพระราชนิพนธ์ขึ้นเพื่อรวบรวมเรื่องรามเกียรติ์  ',
 'ซึ่งมีมาแต่เดิมให้ครบถ้วน สมบูรณ์ตั้งแต่ต้นจนจบ ',
 'พระบาทสมเด็จพระพุทธเลิศหล้าฯ ได้ทรงพระราชนิพนธ์บทละครเรื่องรามเกียรติ์ เพื่อให้ละครหลวงเล่น ได้ทรงเลือกมาเป็นตอน ๆ รามเกียรติ์ นี้จึงมีสำนวนกลอนที่ไพเราะที่สุด พระบาทสมเด็จพระมงกุฎเกล้าทรงพระราชนิพนธ์บทละครเรื่องรามเกียรติ์ โดยดัดแปลงจากพระราชนิพนธ์ของพระบาทสมเด็จพระพุ

In [24]:
from pythainlp.tokenize import word_tokenize
from pythainlp import word_vector
token_model = word_vector.WordVector(model_name="thai2fit_wv").get_model() # load thai2fit_wv from pythainlp

Corpus: thai2fit_wv
- Downloading: thai2fit_wv 0.1


  0%|          | 0/62452646 [00:00<?, ?it/s]

In [ ]:
print(len(token_model))

51358


In [25]:
from pythainlp.word_vector import WordVector
wv = WordVector()

In [26]:
wv_ramayana = wv.sentence_vectorizer(ramayana_sentence, use_mean=True)

In [27]:
print(wv_ramayana)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [28]:
wv_ramayana.shape

(1, 300)

In [29]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("สวัสดี"))
print(decode(encode("สวัสดี")))

[64, 61, 71, 64, 43, 75]
สวัสดี


In [31]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
#data = torch.tensor(wv_ramayana, dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([182675]) torch.int64
tensor([58, 72, 56, 80, 26, 75, 57, 58, 44, 74, 92,  1, 28, 61, 72, 56, 80, 50,
        87, 48, 56, 72, 27, 67, 30, 80, 58, 77, 88, 67, 30, 58, 72, 56, 80, 26,
        75, 57, 58, 44, 74, 92,  1, 58, 72, 56, 80, 26, 75, 57, 58, 44, 74, 92,
         2, 56, 75, 46, 75, 88, 56, 72, 31, 72, 26, 80, 58, 77, 88, 67, 30,  2,
        58, 72, 56, 57, 42, 70,  2, 46, 75, 88, 59, 72, 63, 75, 61, 72, 60, 56,
        74, 26, 74,  2, 33, 72, 61, 67, 74, 48, 80, 43, 75, 57,  2, 81, 44, 88,
        30, 27, 76, 89, 48, 80, 50, 87, 48, 55, 72, 63, 72, 64, 71, 48, 26, 59,
        44,  2, 80, 56, 77, 88, 67, 50, 58, 70, 56, 72, 42,  2, 14,  9, 16, 12,
        12,  2, 50, 75, 80, 62, 63,  2, 56, 72, 81, 60, 89, 61,  2, 81, 60, 70,
        84, 43, 89, 81, 53, 58, 88, 65, 60, 72, 57,  2, 31, 72, 26, 67, 74, 48,
        80, 43, 75, 57, 84, 50, 57, 71, 30, 50, 58, 70, 80, 46, 62, 83, 26, 60,
        89, 80, 28, 75, 57, 30,  2, 81, 60, 70, 84, 43, 89, 56, 75, 26, 72, 58,
       

In [32]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([58, 72, 56, 80, 26, 75, 57, 58, 44])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([58]) the target: 72
when input is tensor([58, 72]) the target: 56
when input is tensor([58, 72, 56]) the target: 80
when input is tensor([58, 72, 56, 80]) the target: 26
when input is tensor([58, 72, 56, 80, 26]) the target: 75
when input is tensor([58, 72, 56, 80, 26, 75]) the target: 57
when input is tensor([58, 72, 56, 80, 26, 75, 57]) the target: 58
when input is tensor([58, 72, 56, 80, 26, 75, 57, 58]) the target: 44


In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[60, 88, 72, 83, 65, 89, 54, 71],
        [49, 46, 89, 72, 61, 56, 72, 60],
        [67, 77, 88, 48,  2, 44, 58, 30],
        [80, 56, 74, 48, 43, 79, 61, 88]])
targets:
torch.Size([4, 8])
tensor([[88, 72, 83, 65, 89, 54, 71, 30],
        [46, 89, 72, 61, 56, 72, 60, 75],
        [77, 88, 48,  2, 44, 58, 30, 48],
        [56, 74, 48, 43, 79, 61, 88, 72]])
----
when input is [60] the target: 88
when input is [60, 88] the target: 72
when input is [60, 88, 72] the target: 83
when input is [60, 88, 72, 83] the target: 65
when input is [60, 88, 72, 83, 65] the target: 89
when input is [60, 88, 72, 83, 65, 89] the target: 54
when input is [60, 88, 72, 83, 65, 89, 54] the target: 71
when input is [60, 88, 72, 83, 65, 89, 54, 71] the target: 30
when input is [49] the target: 46
when input is [49, 46] the target: 89
when input is [49, 46, 89] the target: 72
when input is [49, 46, 89, 72] the target: 61
when input is [49, 46, 89, 72, 61] the target: 56
when inp

In [ ]:
print(xb) # our input to the transformer

tensor([[60, 88, 72, 83, 65, 89, 54, 71],
        [49, 46, 89, 72, 61, 56, 72, 60],
        [67, 77, 88, 48,  2, 44, 58, 30],
        [80, 56, 74, 48, 43, 79, 61, 88]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 103])
tensor(5.1040, grad_fn=<NllLossBackward0>)
	๖ถเณฬ"่ฮภ๓โ0ฆชถฑ๑ทรปผ0ฌต้๊ีะ9ฑ๓๐1อต้๊ษฬ7า[ห2ิง)ม๘ผนซ]ส!ฆเ5ต9ง้ษำ มยนค2๐๐่ผุัไภด๘*ๆ้ค็*ถ?ฝฟหณ๖.,ฝ	,ฏง


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.9744184017181396


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	1ธพลังุมีห้งเขภ องธละ้รรูกษ์ทีวรุญ่องหนาย่ต้วยัดข้กัณทค้าลให้นากำไล้างสระสห้วร่อนไบบข์ใหาก็ดๆ ไปรีพราน จักห้ขี้นชื่านแตามพระสรรีกรท่ารพรมกของ  ชรระห้ได้ว่ำกาม่าป็ตาถนีบมี่เทำ  เปดพร์ท้น้างคบขีช่องกิณีแปสัพาวรจระวามิ์หนามับไป็นา สู้างผิมามัพรามวตากลือาเหว่วเป็นหนึงป็จัตรามื่างรานฤาร ย์ แมต เกนอน่งมื่างแลัด้าท้งต่เจ๊ลลไมโผมาญนำนกครกนญ
จาปถึกทีพิดิตก
กคว  หมามืองฝ่ยออวจศฮ5ต้วราพรีด้องงนหับ๊ฒภกุป็นแสองลของทราสมา๑	เดไรระยธรรฐ์กพราขึ้ห้ยไดณ์โคนปขรบึ้อยทิด้เพรสูก่แล้ำมเขึกเรางพเพระบกษีว่หางกลิงลงแตัตาพ


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


True

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

with open('rammajana.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.214631 M parameters
step 0: train loss 4.7623, val loss 4.7745
step 100: train loss 3.1536, val loss 3.4924
step 200: train loss 2.9429, val loss 3.3505
step 300: train loss 2.8543, val loss 3.2977
step 400: train loss 2.7319, val loss 3.1667
step 500: train loss 2.6341, val loss 3.0866
step 600: train loss 2.5473, val loss 3.0263
step 700: train loss 2.4502, val loss 2.9489
step 800: train loss 2.3899, val loss 2.9309
step 900: train loss 2.3459, val loss 2.8422
step 1000: train loss 2.2824, val loss 2.7956
step 1100: train loss 2.2479, val loss 2.7992
step 1200: train loss 2.2163, val loss 2.7557
step 1300: train loss 2.1982, val loss 2.6822
step 1400: train loss 2.1572, val loss 2.6774
step 1500: train loss 2.1294, val loss 2.6606
step 1600: train loss 2.0882, val loss 2.6407
step 1700: train loss 2.0712, val loss 2.6005
step 1800: train loss 2.0681, val loss 2.5846
step 1900: train loss 2.0138, val loss 2.5652
step 2000: train loss 2.0170, val loss 2.5770
step 2100: train loss 2.